// Code generated by "stringer -type TokenKind -linecomment"; DO NOT EDIT.

package language

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenLBrace-40]
	_ = x[TokenRBrace-41]
	_ = x[TokenLBrack-91]
	_ = x[TokenRBrack-93]
	_ = x[TokenLCurl-123]
	_ = x[TokenRCurl-125]
	_ = x[TokenQuote-39]
	_ = x[TokenSymbol-107]
	_ = x[TokenKeyword-108]
	_ = x[TokenInt-109]
	_ = x[TokenFloat-110]
	_ = x[TokenStr-111]
}

const (
	_TokenKind_name_0 = "'()"
	_TokenKind_name_1 = "["
	_TokenKind_name_2 = "]"
	_TokenKind_name_3 = "symbol:keywordintegerfloatstring"
	_TokenKind_name_4 = "{"
	_TokenKind_name_5 = "}"
)

var (
	_TokenKind_index_0 = [...]uint8{0, 1, 2, 3}
	_TokenKind_index_3 = [...]uint8{0, 6, 14, 21, 26, 32}
)

func (i TokenKind) String() string {
	switch {
	case 39 <= i && i <= 41:
		i -= 39
		return _TokenKind_name_0[_TokenKind_index_0[i]:_TokenKind_index_0[i+1]]
	case i == 91:
		return _TokenKind_name_1
	case i == 93:
		return _TokenKind_name_2
	case 107 <= i && i <= 111:
		i -= 107
		return _TokenKind_name_3[_TokenKind_index_3[i]:_TokenKind_index_3[i+1]]
	case i == 123:
		return _TokenKind_name_4
	case i == 125:
		return _TokenKind_name_5
	default:
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
