// Code generated by "stringer -type=TokenKind -linecomment"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenEnd-0]
	_ = x[TokenLeftPar-1]
	_ = x[TokenRightPar-2]
	_ = x[TokenString-3]
	_ = x[TokenAtom-4]
}

const _TokenKind_name = "TokenEnd()stringatom"

var _TokenKind_index = [...]uint8{0, 8, 9, 10, 16, 20}

func (i TokenKind) String() string {
	if i < 0 || i >= TokenKind(len(_TokenKind_index)-1) {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[i]:_TokenKind_index[i+1]]
}
